site_name: "Artificial Intelligence"
site_author: "Emma Tosch (etosch@uvm.edu)"
site_description: "Public Course Website for CS295A/CS395D S2022 at Universtiy of Vermont"
docs_dir: "src"
use_directory_urls: false
titles_only: true
site_url: "https://uvm.edu/~etosch/CS295A-S22"
repo_url: "https://github.com/uvm-maple/CS295A-S22"
repo_name: "Github"
edit_url: "tree/main/src/"

theme: 
  # name: "rtd-dropdown"
  name: "material"

markdown_extensions:
  - attr_list
  - extra
  - sane_lists
  - tables
  - nl2br

nav:
  - "index.md"
  - "syllabus.md"
  - "schedule.md"
  - "blogging_guidelines.md"
  - "blog.md"
  - "Programming Assignments":
    - "assignments/1/programming_assignment_1.md"
    - "assignments/2/programming_assignment_2.md"
  - "covid_policies.md"
  - "UVM_resources.md"
  

plugins: 
  - rss
  - blogging:
      dirs:
        - blog
  - diagrams

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

      

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
